package net.kgomc.zelda.configuration.registry;

import de.exlll.configlib.YamlConfigurationProperties;
import de.exlll.configlib.YamlConfigurationStore;
import net.kgomc.zelda.configuration.annotation.ConfigHeader;
import net.kgomc.zelda.configuration.annotation.ZeldaConfig;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.locks.ReadWriteLock;
import java.util.concurrent.locks.ReentrantReadWriteLock;
import java.util.logging.Logger;

/**
 * Holds and manages all registered {@link ZeldaConfig} instances.
 *
 * <p>Thread-safe via a {@link ReentrantReadWriteLock} — multiple threads
 * can read configs concurrently; reload operations take an exclusive write lock.</p>
 *
 * <h2>Registration</h2>
 * <pre>{@code
 * // Simple — all defaults
 * registry.register(SettingsConfig.class);
 *
 * // With per-file property overrides
 * registry.register(EconomyConfig.class, props -> props
 *     .toBuilder()
 *     .outputNulls(true)
 *     .build()
 * );
 * }</pre>
 *
 * <h2>Retrieval</h2>
 * <pre>{@code
 * SettingsConfig settings = registry.get(SettingsConfig.class);
 * }</pre>
 *
 * <h2>Reload</h2>
 * <pre>{@code
 * registry.reloadAll();           // all configs
 * registry.reload(SettingsConfig.class); // single config
 * }</pre>
 */
public final class ConfigurationRegistry {

    private final Path baseDir;
    private final Logger logger;

    /** Stores entries in registration order for predictable reload sequencing. */
    private final Map<Class<?>, ConfigurationEntry<?>> entries = new LinkedHashMap<>();

    /** Many concurrent reads allowed; reload takes an exclusive write lock. */
    private final ReadWriteLock lock = new ReentrantReadWriteLock();

    /**
     * Shared base properties inherited by all configs unless overridden via
     * {@link PropertiesCustomizer} or {@link ConfigHeader}.
     */
    private final YamlConfigurationProperties sharedProperties;

    public ConfigurationRegistry(Path baseDir, Logger logger) {
        this.baseDir = baseDir;
        this.logger  = logger;
        this.sharedProperties = buildSharedProperties();
    }

    /**
     * Builds the base properties.
     *
     * <p>Uses {@code BukkitDefaultProperties} (which registers ItemStack, Location,
     * etc. serializers) when running on Paper. Falls back to the plain YAML builder
     * on Velocity or in test environments where Paper is not present.</p>
     */
    private static YamlConfigurationProperties buildSharedProperties() {
        boolean isPaper = isPaperPresent();
        String header = "Generated by Zelda Configuration — do not remove existing keys.";

        if (isPaper) {
            try {
                // de.exlll.configlib.BukkitConfigurationProperties or ConfigLib.BUKKIT_DEFAULT_PROPERTIES
                // Try the stable API first (configlib-paper 4.x)
                Class<?> propsClass = Class.forName("de.exlll.configlib.BukkitConfigurationProperties");
                Object instance = propsClass.getMethod("newBuilder").invoke(null);
                instance = instance.getClass().getMethod("header", String.class).invoke(instance, header);
                return (YamlConfigurationProperties) instance.getClass().getMethod("build").invoke(instance);
            } catch (Exception e1) {
                try {
                    // Fallback: ConfigLib.BUKKIT_DEFAULT_PROPERTIES static field
                    Class<?> configLib = Class.forName("de.exlll.configlib.ConfigLib");
                    var bukkit = (YamlConfigurationProperties) configLib
                            .getField("BUKKIT_DEFAULT_PROPERTIES").get(null);
                    return bukkit.toBuilder().header(header).build();
                } catch (Exception e2) {
                    // Neither worked — fall through to plain builder
                }
            }
        }

        // Velocity, tests, or Paper configlib not available
        return YamlConfigurationProperties.newBuilder()
                .header(header)
                .build();
    }

    private static boolean isPaperPresent() {
        try {
            Class.forName("org.bukkit.Bukkit");
            return true;
        } catch (ClassNotFoundException e) {
            return false;
        }
    }

    /**
     * Registers a config class using its {@link ZeldaConfig} and optional
     * {@link ConfigHeader} annotations to determine file path and header.
     *
     * <p>Uses ConfigLib's {@code update()} — creates the file with defaults if
     * it doesn't exist, and fills missing keys if it does.</p>
     *
     * @param type a class annotated with {@code @ZeldaConfig} (and {@code @Configuration})
     * @throws IllegalArgumentException if {@code @ZeldaConfig} is missing
     * @throws IllegalStateException    if the type is already registered
     */
    public <T> void register(Class<T> type) {
        register(type, null);
    }

    /**
     * Registers a config class with a per-file {@link PropertiesCustomizer}.
     *
     * <p>The customizer receives the shared base properties (already incorporating
     * any {@link ConfigHeader} annotation) and returns the final properties to use.
     * Pass {@code null} to use defaults.</p>
     *
     * <pre>{@code
     * registry.register(EconomyConfig.class, props -> props
     *     .toBuilder()
     *     .outputNulls(true)
     *     .build()
     * );
     * }</pre>
     */
    public <T> void register(Class<T> type, PropertiesCustomizer customizer) {
        ZeldaConfig annotation = requireAnnotation(type);
        Path filePath = resolveFilePath(annotation);

        lock.writeLock().lock();
        try {
            if (entries.containsKey(type)) {
                throw new IllegalStateException("Config already registered: " + type.getSimpleName());
            }

            logger.info("[Zelda/Config] Loading " + type.getSimpleName()
                    + " → " + baseDir.relativize(filePath));

            YamlConfigurationProperties properties = buildProperties(type, customizer);
            YamlConfigurationStore<T> store = new YamlConfigurationStore<>(type, properties);

            // update() = load + fill missing keys with defaults + save.
            // Creates the file from scratch if it doesn't exist.
            T instance = store.update(filePath);

            entries.put(type, new ConfigurationEntry<>(type, instance, store, filePath));
            logger.info("[Zelda/Config] Loaded: " + filePath.getFileName());

        } finally {
            lock.writeLock().unlock();
        }
    }

    // -----------------------------------------------------------------------
    // Retrieval
    // -----------------------------------------------------------------------

    /**
     * Returns the live config instance for the given type.
     *
     * @throws IllegalArgumentException if the type was never registered
     */
    @SuppressWarnings("unchecked")
    public <T> T get(Class<T> type) {
        lock.readLock().lock();
        try {
            ConfigurationEntry<?> entry = entries.get(type);
            if (entry == null) {
                throw new IllegalArgumentException(
                        "Config not registered: " + type.getSimpleName()
                                + ". Did you call registry.register(" + type.getSimpleName() + ".class)?");
            }
            return (T) entry.instance();
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Returns the live config instance wrapped in {@link Optional},
     * or empty if the type was never registered.
     */
    @SuppressWarnings("unchecked")
    public <T> Optional<T> find(Class<T> type) {
        lock.readLock().lock();
        try {
            ConfigurationEntry<?> entry = entries.get(type);
            return entry == null ? Optional.empty() : Optional.of((T) entry.instance());
        } finally {
            lock.readLock().unlock();
        }
    }

    // -----------------------------------------------------------------------
    // Reload
    // -----------------------------------------------------------------------

    /**
     * Reloads all registered configs from disk.
     * Takes an exclusive write lock — concurrent reads block until complete.
     * A failure in one config is logged but does not prevent others from reloading.
     */
    public void reloadAll() {
        lock.writeLock().lock();
        try {
            logger.info("[Zelda/Config] Reloading " + entries.size() + " config(s)...");
            entries.replaceAll((type, entry) -> reloadEntry(entry));
            logger.info("[Zelda/Config] Reload complete.");
        } finally {
            lock.writeLock().unlock();
        }
    }

    /**
     * Reloads a single registered config from disk.
     *
     * @throws IllegalArgumentException if the type was never registered
     */
    public <T> void reload(Class<T> type) {
        lock.writeLock().lock();
        try {
            ConfigurationEntry<?> entry = entries.get(type);
            if (entry == null) {
                throw new IllegalArgumentException("Config not registered: " + type.getSimpleName());
            }
            logger.info("[Zelda/Config] Reloading " + type.getSimpleName() + "...");
            entries.put(type, reloadEntry(entry));
        } finally {
            lock.writeLock().unlock();
        }
    }

    // -----------------------------------------------------------------------
    // Internals
    // -----------------------------------------------------------------------

    /**
     * Resolves the final file path from the annotation:
     * {@code baseDir / [path/] / value}
     */
    private Path resolveFilePath(ZeldaConfig annotation) {
        String subPath = annotation.path();
        if (subPath == null || subPath.isBlank()) {
            return baseDir.resolve(annotation.value());
        }
        return baseDir.resolve(subPath).resolve(annotation.value());
    }

    /**
     * Builds the final {@link YamlConfigurationProperties} for a config type:
     * 1. Start with sharedProperties
     * 2. Apply {@link ConfigHeader} if present (overrides shared header)
     * 3. Apply {@link PropertiesCustomizer} if provided (full override)
     */
    private <T> YamlConfigurationProperties buildProperties(Class<T> type, PropertiesCustomizer customizer) {
        YamlConfigurationProperties base = sharedProperties;

        // Step 2: @ConfigHeader overrides the shared header for this file
        ConfigHeader headerAnnotation = type.getAnnotation(ConfigHeader.class);
        if (headerAnnotation != null) {
            String header = String.join("\n", headerAnnotation.value());
            base = base.toBuilder().header(header).build();
        }

        // Step 3: caller-supplied customizer has final say
        if (customizer != null) {
            base = customizer.customize(base);
        }

        return base;
    }

    @SuppressWarnings("unchecked")
    private <T> ConfigurationEntry<T> reloadEntry(ConfigurationEntry<?> entry) {
        ConfigurationEntry<T> e = (ConfigurationEntry<T>) entry;
        try {
            T freshInstance = e.store().update(e.path());
            return new ConfigurationEntry<>(e.type(), freshInstance, e.store(), e.path());
        } catch (Exception ex) {
            logger.severe("[Zelda/Config] Failed to reload " + e.type().getSimpleName()
                    + ": " + ex.getMessage() + " — keeping previous values.");
            return e; // keep stale instance rather than crashing
        }
    }

    private static <T> ZeldaConfig requireAnnotation(Class<T> type) {
        ZeldaConfig annotation = type.getAnnotation(ZeldaConfig.class);
        if (annotation == null) {
            throw new IllegalArgumentException(
                    type.getSimpleName() + " is missing @ZeldaConfig. "
                            + "Annotate it with @ZeldaConfig(\"yourfile.yml\")."
            );
        }
        return annotation;
    }
}